---

- name: Deploy Docker host in Ubuntu 16.04 LTS
  hosts: dockerservers
  remote_user: ubuntu
  become: true
  become_method: sudo

  vars_files:
    - vars/users.yml

  roles:
    - common
    - users

  tasks:
    - name: Install packages to allow apt to use a repository over HTTPS
      apt: name={{ item }} state=latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker's official GPG key
      apt_key: 
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add Docker's repository
      apt_repository: 
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present
        filename: 'docker'

    - name: Install the latest version of Docker CE
      apt:
        name: docker-ce
        update_cache: yes
        state: latest

    - name: Make sure a Docker service is running an enable
      systemd: state=started name=docker.service enabled=yes
